// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;
using System.Linq;
using NewsChronicle.Data.Utils;
using NewsChronicle.Data.ViewModel;
using NewsChronicle.Data;

namespace NewsChronicle
{
	public partial class SettingsViewController : UIViewController, IUITableViewDataSource, IUITableViewDelegate, IUITextFieldDelegate
	{
        #region Properties

        private readonly AppSettingsViewModel _viewModel;

        private UITableView _dropDownTableView; // the drop down table view
        private UIView _dropDownView;           // the drop down view

        #endregion

        public SettingsViewController (IntPtr handle) : base (handle)
		{
            _viewModel = ViewModelLocator.Instance.GetInstanceViewModelInstance<AppSettingsViewModel>();
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            languageOptions.Text = _viewModel.OptionDict.FirstOrDefault(x => x.Value == _viewModel.AppArticleLanguage).Key;

            CreateDropDownView(new CGRect(languageOptions.Frame.X, languageOptions.Frame.Y,
                languageOptions.Frame.Width, 43 * _viewModel.OptionDict.Count));
        }

        #region UIMethods

        private void CreateDropDownView(CGRect frameForDropDown)
        {
            _dropDownView = new UIView(frameForDropDown);
            _dropDownTableView = new UITableView(new CGRect(0, 0, frameForDropDown.Width, frameForDropDown.Height));
            _dropDownTableView.RegisterClassForCellReuse(typeof(UITableViewCell), "DropDownCell");
            _dropDownTableView.DataSource = this;
            _dropDownTableView.Delegate = this;
            languageOptions.Delegate = this;
            _dropDownView.AddSubview(_dropDownTableView);
            AddShadowToDropDown();
        }

        private void AddShadowToDropDown()
        {
            var shadowPath = UIBezierPath.FromRect(_dropDownView.Bounds);
            _dropDownView.Layer.MasksToBounds = false;
            _dropDownView.Layer.ShadowColor = UIColor.Black.CGColor;
            _dropDownView.Layer.ShadowOffset = new CGSize(width: 0, height: 0.5);
            _dropDownView.Layer.ShadowOpacity = 0.2f;
            _dropDownView.Layer.ShadowPath = shadowPath.CGPath;
            _dropDownTableView.ClipsToBounds = true;
        }

        #endregion

        #region UITableViewDelegate

        [Export("tableView:didSelectRowAtIndexPath:")]
        public void RowSelected(UITableView tableView, NSIndexPath indexPath)
        {
            languageOptions.Text = _viewModel.OptionDict.ElementAt(indexPath.Row).Key;
            _viewModel.SetAppArticleLanguage(_viewModel.OptionDict[languageOptions.Text]);
            _dropDownView.RemoveFromSuperview();
        }

        #endregion

        #region UITableViewDataSource

        [Export("tableView:numberOfRowsInSection:")]
        public nint RowsInSection(UITableView tableView, nint section)
        {
            return _viewModel.OptionDict.Count;
        }

        [Export("tableView:cellForRowAtIndexPath:")]
        public UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
        {
            UITableViewCell cell = tableView.DequeueReusableCell("DropDownCell");
            cell.TextLabel.Text = _viewModel.OptionDict.ElementAt(indexPath.Row).Key;
            cell.ImageView.Image = UIImage.FromBundle(Utilities.GetCountryIconIdentifier(_viewModel.OptionDict[cell.TextLabel.Text]));
            return cell;
        }

        #endregion

        #region IUITextFieldDelegate

        [Export("textFieldShouldBeginEditing:")]
        public bool ShouldBeginEditing(UITextField textField)
        {
            View.AddSubview(_dropDownView);
            UIApplication.SharedApplication.KeyWindow.BringSubviewToFront(_dropDownTableView);
            return false;
        }

        [Export("tableView:viewForFooterInSection:")]
        public UIView GetViewForFooter(UITableView tableView, nint section)
        {
            UIView footerView = new UIView(new CGRect(0, 0, 0, 0));
            return footerView;
        }

        [Export("tableView:heightForFooterInSection:")]
        public nfloat GetHeightForFooter(UITableView tableView, nint section)
        {
            return 1;
        }

        #endregion
    }
}
